name: Zakfarm UI Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [main, initial]
  pull_request:
    branches: [main, initial]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        id: test
        run: |
          npx playwright test --reporter=list,html 2>&1 | tee test_output.log || true
        continue-on-error: true
        env:
          CI: true

      - name: Parse test results
        id: parse-results
        run: |
          PASSED=$(grep -o '[0-9]\+ passed' test_output.log | grep -o '[0-9]\+' | tail -1 || echo "0")
          FAILED=$(grep -o '[0-9]\+ failed' test_output.log | grep -o '[0-9]\+' | tail -1 || echo "0")
          FLAKY=$(grep -o '[0-9]\+ flaky' test_output.log | grep -o '[0-9]\+' | tail -1 || echo "0")
          TOTAL=$((PASSED + FAILED))
          if [ $TOTAL -gt 0 ]; then
            PASS_RATE=$(echo "scale=2; $PASSED * 100 / $TOTAL" | bc)
          else
            PASS_RATE="0.00"
          fi
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT
          echo "flaky=$FLAKY" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "pass_rate=$PASS_RATE" >> $GITHUB_OUTPUT

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test_output.log

      # Email sending is commented out due to authentication errors with Gmail
      # To fix this error:
      # 1. Enable 2-step verification for your Gmail account
      # 2. Create an App Password (https://myaccount.google.com/apppasswords)
      # 3. Use that App Password in GitHub secrets instead of your regular password
      # 4. Uncomment the section below once fixed
      
      # - name: Send Playwright HTML report via email
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     secure: true
      #     username: ${{ secrets.MAIL_USERNAME }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: Zakfarm Playwright Test Results - ${{ steps.parse-results.outputs.failed == '0' && 'SUCCESS' || 'FAILURE' }}
      #     to: gurovvic@gmail.com
      #     from: GitHub Actions
      #     html_body: |
      #       <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      #         <h2 style="color: #2563eb;">Zakfarm Playwright Test Results</h2>
      #         <p><strong>Pass Rate:</strong> ${{ steps.parse-results.outputs.pass_rate }}%</p>
      #         <p><strong>Total:</strong> ${{ steps.parse-results.outputs.total }}</p>
      #         <p><strong>Passed:</strong> ${{ steps.parse-results.outputs.passed }}</p>
      #         <p><strong>Failed:</strong> ${{ steps.parse-results.outputs.failed }}</p>
      #         <p><strong>Flaky:</strong> ${{ steps.parse-results.outputs.flaky }}</p>
      #         <p>
      #           <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a>
      #         </p>
      #       </div>
      #     attachments: |
      #       playwright-report/index.html
